
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: app
  name: webapp
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: app
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: app
    serviceAccount: webapp
    audiences:
      - https://kubernetes.default.svc.cluster.local