
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: app
  name: webapp
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: app
spec:
  method: kubernetes
  mount: demo-auth-mount
  kubernetes:
    role: role1
    serviceAccount: webapp
    audiences:
      - vault